{
 "title": "Kandula - Monitoring",
 "tags": [ "imported" ],
 "refresh": "25s",
 "panels": [
  {
   "title": "AVG Duration Time per Method",
   "type": "timeseries",
   "description": "Compute the average of a measurement over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(opsschool_monitor_flask_request_processing_seconds_sum[$__rate_interval]) / rate(opsschool_monitor_flask_request_processing_seconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration time - Home  - 0.95",
   "type": "timeseries",
   "description": "histogram_quantile 0.95",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(opsschool_monitor_flask_request_processing_seconds_bucket{method=\"home\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVG Requests per Second (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(opsschool_monitor_flask_page_count_total{exported_endpoint!=\"metrics\"}[$__rate_interval]) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration time - Instances  - 0.95",
   "type": "timeseries",
   "description": "histogram_quantile 0.95",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(opsschool_monitor_flask_request_processing_seconds_bucket{method=\"instances\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVG Page Hits",
   "type": "gauge",
   "description": "Calc the RPM multiple the time range with increase func.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(opsschool_monitor_flask_page_count_total{exported_endpoint!=\"metrics\"}[$__rate_interval])",
     "legendFormat": "{{export-endpoint}}"
    }
   ]
  },
  {
   "title": "Duration time - Scheduler  - 0.95",
   "type": "timeseries",
   "description": "histogram_quantile 0.95",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(opsschool_monitor_flask_request_processing_seconds_bucket{method=\"scheduler\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration time - Health  - 0.95",
   "type": "timeseries",
   "description": "histogram_quantile 0.95",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(opsschool_monitor_flask_request_processing_seconds_bucket{method=\"health\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration time - About  - 0.95",
   "type": "timeseries",
   "description": "histogram_quantile 0.95",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(opsschool_monitor_flask_request_processing_seconds_bucket{method=\"about\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}