apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuar-ingress
  namespace: kandula
spec:
  ingressClassName: nginx
  rules:
  - host: check.lirondadon.link
    http:
      paths:
      - backend:
          service:
            name: kuar-svc
            port:
              number: 80
        path: /
        pathType: Prefix