# Contains values that affect multiple components of the chart.
global:
  # The main enabled/disabled setting.
  # If true, servers, clients, Consul DNS and the Consul UI will be enabled.
  enabled: false
  # The prefix used for all resources created in the Helm chart.
  name: consul
  # The consul image version.
  image: hashicorp/consul:1.15.1
  # The name of the datacenter that the agents should register as.
  datacenter: opsschool
  gossipEncryption:
    secretName: "consul-gossip-encryption-key"
    secretKey: "key"
# Configures values that configure the Consul server cluster.
server:
  enabled: true
  # The number of server agents to run. This determines the fault tolerance of the cluster.
  replicas: 3
# Contains values that configure the Consul UI.
ui:
  enabled: true
dns:
  enabled: true
# client:
#   enabled: true
#   join:
#     - "provider=aws tag_key=consul_connect tag_value=true"
