apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::902770729603:role/group_1-eks-node-group-20230331122716138300000008
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::902770729603:role/group_2-eks-node-group-20230331122716135000000007
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::902770729603:role/eks-developers-role
      username: eks-developers-role
      groups:
        - developers
  mapUsers: |
    - userarn: arn:aws:iam::902770729603:user/employee2
      username: employee2
      groups:
        - system:masters
  