---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: jenkins
  name: eks-developers-access
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - pods/status
  - secrets
  - configmaps
  - podtemplates
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - deletecollection
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: jenkins
  name: eks-developers-access-binding
subjects:
- kind: Group
  name: developers
  namespace: jenkins
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: eks-developers-access
  apiGroup: rbac.authorization.k8s.io
