apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: jenkins
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: "/jenkins"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/jenkins)$ http://$best_http_host$1/ permanent;
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - jenkins-k8s.lirondadon.link
      secretName: echo-tls
  rules:
  - host: jenkins-k8s.lirondadon.link
    http:
      paths:
      - backend:
          service:
            name: jenkins-svc
            port:
              number: 80
        path: /jenkins
        pathType: Exact