apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::902770729603:role/group_2-eks-node-group-20230520065204358600000009
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::902770729603:role/group_1-eks-node-group-20230520065204355900000008
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::902770729603:role/AdministratorAccess
      username: admin
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2023-05-20T07:03:18Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "9612"
  uid: 9aefde48-192f-4fd8-830c-ad51f82d2821
