---

# - name: Show facts available on the system
#   debug:
#     var: ansible_facts    

 - name: Installing consul on ubuntu
   include: ubuntu.yml
   when:  ansible_facts['distribution'] == 'Ubuntu'