---
- name: Installing dependencies apt
  apt:
    pkg:
      - python3-pip
      - dnsmasq
    update_cache: true
    state: latest

- name: Installing dependencies pip
  pip:
    name:
    - boto3
    - botocore
    - awscli
    extra_args: --upgrade
    executable: pip3

- name: "Ansible | Creating dnsmasq"
  copy:
    dest: "/etc/dnsmasq.d/10-consul"
    content: |
      # Enable forward lookup of the 'consul' domain:
      server=/consul/127.0.0.1#8600
  notify:
    - Restarting dnsmasq

- name: "Ansible | Update resolved.conf"
  blockinfile:
    path: "/etc/systemd/resolved.conf"
    block: |
      [Resolve]
      DNS=127.0.0.1
      Domains=~consul
  notify:
    - Restarting systemd-resolved.service

- name: Adding Consul GPG apt Key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Linux Standard Base and Distribution information
  command: lsb_release -sc
  register: lsb_release
    
- name: Adding Consul Repository
  apt_repository:
    repo: "deb https://apt.releases.hashicorp.com {{ lsb_release.stdout }} main"
    state: present
    update_cache: true

- name: Installing Consul  
  apt:
    update_cache: yes
    pkg:
      - consul
    state: latest

- name: Fetch instance metadata
  shell: ip -o route get to 169.254.169.254 | sed -n 's/.*src \([0-9.]\+\).*/\1/p'
  register: PRIVATE_IP

- name: print var PRIVATE_IP
  debug:
    var: "{{ PRIVATE_IP.stdout }}"

- name: "Ansible | Modifying consul.hcl"
  template:
    src: config.hcl.j2
    dest: "/etc/consul.d/consul.hcl"
    owner: consul
    group: consul

- name: Creating /run/consul directory
  file:
    path: /run/consul
    state: directory
    owner: consul
    group: consul
    recurse: yes

- name: Appending "ubuntu" user to "consul" group
  user:
    name: "ubuntu"
    group: "consul"
    append: yes

- name: "Ansible | Creating consul.service"
  template:
    src: consul.service.j2
    dest: "/etc/systemd/system/consul.service"
    owner: consul
    group: consul

- name: Starting consul.service
  systemd:
    name: consul.service
    daemon_reload: true
    enabled: true
    state: started

- name: "Ansible | Get EKS cluster name from S3"
  amazon.aws.aws_s3:
    bucket: "{{ s3_bucket }}"
    mode: get
    object: "cluster_name"
    dest: /usr/local/cluster_name.txt

- name: print var EKS_CLUSTER_NAME
  command: "cat /usr/local/cluster_name.txt"
  register: EKS_CLUSTER_NAME

- name: "Ansible | Update k8s context"
  command: "aws eks --region={{ aws_region }} update-kubeconfig --name {{ EKS_CLUSTER_NAME.stdout }}"

- name: "Ansible | Modifying postgres.hcl"
  template:
    src: postgres.hcl.j2
    dest: "/etc/consul.d/postgres.hcl"
    owner: consul
    group: consul
  notify:
    - Restarting consul