---
plugin: aws_ec2
regions:
  - us-east-2

keyed_groups:
  - key: tags.Type

filters:
  tag:consul_server: "true"
  instance-state-name : running
hostnames:
  - ip-address
  - private-ip-address

# compose:
#   ansible_host: public_ip_address